name: 'Azure Files Upload'
description: 'This action uses the Azure CLI to upload the selected directory to Azure Files.'
auther: 'rnakamine'
inputs:
  connection_string:
    description: 'The connection string for the storage account.'
    required: true
  source:
    description: 'The directory to upload files from.'
    required: true
  destination:
    description: 'The destination of the upload operation.'
    required: true
  extra_args:
    description: 'Extra arguments. Can passing flags like `--pattern` or `--destination-path`'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
