name: 'Azure Files Upload'
description: 'This action uses the Azure CLI to upload the selected directory to Azure Files.'
auther: 'rnakamine'
inputs:
  connection_string:
    description: 'The connection string for the storage account.'
    required: true
  source:
    description: ''
    required: true
  destination:
    description: ''
    required: true
  extra_args:
    description: ''
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
